In [31]:
import numpy as np
u = np.diag([-1,-1,-1])# u - она же и нижнетреугодьная и верхне-ая
u

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [106]:
s=np.dot(u,np.transpose(u))
s 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [97]:
m = np.array([[1, 2], [2, 5]], dtype=np.float32)
det = np.linalg.det(m)
print(m)
print(det)

[[1. 2.]
 [2. 5.]]
1.0


In [102]:
m = np.array([[2, 2],
              [1, 3]])
w, v = np.linalg.eig(m)
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]
